substitutions:
  _IMAGE_JOBRUNNER: 'asia.gcr.io/${PROJECT_ID}/utako-jobrunner-${_ENVIRONMENT}'
steps:

# fetch config and analyze model
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'gcloud secrets versions access latest --secret=utako-jobrunner-${_ENVIRONMENT}-secret > conf/auth.${_ENVIRONMENT}.conf'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gsutil'
    - 'cp'
    - 'gs://utako-jobrunner-artifacts/model/model_0.yaml'
    - 'conf/model_0.yaml'

# build jobrunner
- name: 'docker'
  entrypoint: 'sh'
  args:
    - '-c'
    - "docker pull ${_IMAGE_JOBRUNNER}:latest || exit 0"
- name: 'docker:20'
  args: [
    'build',
    '--network=cloudbuild',
    '-t', '${_IMAGE_JOBRUNNER}:latest',
    '-t', '${_IMAGE_JOBRUNNER}:${SHORT_SHA}',
    '--cache-from', '${_IMAGE_JOBRUNNER}:latest',
    '-f', 'Dockerfile', '.']

# push container
- name: 'docker'
  args: ['push', '${_IMAGE_JOBRUNNER}:latest']
- name: 'docker'
  args: ['push', '${_IMAGE_JOBRUNNER}:${SHORT_SHA}']

# deploy to cloud run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gcloud'
    - 'run'
    - 'deploy'
    - '${_CLOUDRUN_JOBRUNNER_TARGET}'
    - '--image'
    - '${_IMAGE_JOBRUNNER}:${SHORT_SHA}'
    - '--platform'
    - 'managed'
    - '--region'
    - 'asia-northeast1'
    - '--no-allow-unauthenticated'
