dist: 'bionic'
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  global:
    PYTHONPATH: "."
    PYTHON_ENV: "test"

addons:
  apt:
    packages:
      - python3-tk
      - libmysqlclient-dev

install:
  - pip install -r dependencies.dat

script:
  - pytest
