dist: 'bionic'
language: python
python:
  - "3.8"

env:
  global:
    - PYTHONPATH=.
    - PYTHON_ENV=test
addons:
  apt:
    packages:
      - python3-tk
      - libmysqlclient-dev
      - libsndfile1

before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
  - pip install pipenv

install:
  - pipenv install --dev --system --deploy

script:
  - pipenv run pytest --cov=utako -r a -v

after_success:
  - codecov
