dist: 'bionic'
language: python
python:
  - "3.6"

env:
  global:
    PYTHONPATH: "."
    PYTHON_ENV: "test"
    secure: v5FqFMeRDb17rHl/AcBpn//HwV+UXv4Yc0/0S5ewCktl5Pzd7kHhpEP7JdH60rRNS5zhW4WMq564EosZZuBkhIdv9uw/ixK/R1CQGuOj0nH+Cx5kHY/2EenpcEpXiF8g1+lpHfKmP6WyZr1hVy+Zp+NdfAdROPxKMUJPt2tIYThh79C30C457iGQW9FbRixf8R2FRuM596HEGl0GPwt8g3fNYp3pQArnlGYwGhip+aL+1T5jENTzCd88itMK4HU37FGq28ZYxF2LwbJFqZYs579bGjBuDpwXRP6kEUyT5/Qeisu64NpSAi7FXCLDyQv/H77XFp1HGqbt+SICLok2F44F7Qtud3k7O4OGptgd8LCq2h3qvFxC4qQ24EhtAkqur+THBuVx7IJTIeOdiCJJAyERXxP6gg7jq8gXeEi0WTL/YU3j6Ud7t5obHJOW9fr8g0hvSsNhvFyIQZvnKvLkOdlJN1Zs4WUgDmQ7LlPct97PvevRbjbVzfPT19jW4VpzbRCE9HFKPldFLwXgTBIkNvkjzgNwRRGgYdkD54ogEldCuOJ0Jz+US10A7See+M4McRJfkiBFWGlJ1GYZh4UMLliU/fBpLLR37Ln98XfuSniv7MhYXfhA8AJJIC2VCUerIQBVgU6H++tHIqBhOoE+FyuyzPBXHFF91kNiWTQIJhk=
addons:
  apt:
    packages:
      - python3-tk
      - libmysqlclient-dev
      - libsndfile1

before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
  - pip install pipenv

install:
  - |-
    bash -c '
      eval 'set +o history' 2>/dev/null || setopt HIST_IGNORE_SPACE 2>/dev/null
      touch .gitcookies
      chmod 0600 .gitcookies

      git config --global http.cookiefile .gitcookies

      tr , \\t <<\__END__ >>.gitcookies
      ${GIT_COOKIE_SECRET}
      __END__
      eval 'set -o history' 2>/dev/null || unsetopt HIST_IGNORE_SPACE 2>/dev/null
    '
  - pipenv install --dev --system --deploy
  - rm -rf .gitcookies

script:
  - pipenv run pytest --cov=utako -r a -v

after_success:
  - codecov