dist: xenial
language: python
python:
  - "3.5"
  - "3.6"

env:
  global:
    PYTHONPATH: .
    PYTHON_ENV: test

addons:
  apt:
    packages:
      - python3-tk
      - libmysqlclient-dev

install:
  - pip install -r dependencies.dat

script:
  - pytest
