dist: 'bionic'
language: python
python:
  - "3.6"

env:
  global:
    - PYTHONPATH=.
    - PYTHON_ENV=test
addons:
  apt:
    packages:
      - python3-tk
      - libmysqlclient-dev
      - libsndfile1

before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
  - pip install pipenv
  - openssl aes-256-cbc -K $encrypted_5f73c6d3fd42_key -iv $encrypted_5f73c6d3fd42_iv -in .gitcookies.enc -out .gitcookies -d
  - git config --global http.cookiefile .gitcookies

install:
  - git config --global http.cookiefile
  - md5sum .gitcookies
  - pipenv install --dev --system --deploy
  - rm -rf .gitcookies

script:
  - pipenv run pytest --cov=utako -r a -v

after_success:
  - codecov