dist: 'bionic'
language: python
python:
  - "3.6"

env:
  global:
    PYTHONPATH: "."
    PYTHON_ENV: "test"

addons:
  apt:
    packages:
      - python3-tk
      - libmysqlclient-dev

install:
  - pip install pipenv
  - pipenv sync

script:
  - pipenv run pytest
