steps:

# fetch config and analyze model
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'gcloud secrets versions access latest --secret=utako-jobrunner-${_ENVIRONMENT}-secret > conf/auth.${_ENVIRONMENT}.conf'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gsutil'
    - 'cp'
    - 'gs://utako-jobrunner-artifacts/model/model_0.model'
    - 'conf/model_0.model'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gsutil'
    - 'cp'
    - 'gs://utako-jobrunner-artifacts/model/model_0.yaml'
    - 'conf/model_0.yaml'

# Invoke git command to enable google cloud source repositories
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |-
      eval 'set +o history' 2>/dev/null || setopt HIST_IGNORE_SPACE 2>/dev/null
      touch ~/.gitcookies
      chmod 0600 ~/.gitcookies

      git config --global http.cookiefile ~/.gitcookies

      tr , \\t <<\__END__ >>~/.gitcookies
      ${_GIT_COOKIE_SECRET}
      __END__
      eval 'set -o history' 2>/dev/null || unsetopt HIST_IGNORE_SPACE 2>/dev/null

# build container
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - "docker pull asia.gcr.io/$PROJECT_ID/utako-jobrunner-${BRANCH_NAME}:latest || exit 0"
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--network=cloudbuild',
    '-t', 'asia.gcr.io/$PROJECT_ID/utako-jobrunner-${BRANCH_NAME}:latest',
    '-t', 'asia.gcr.io/$PROJECT_ID/utako-jobrunner-${BRANCH_NAME}:${SHORT_SHA}',
    '--cache-from', 'asia.gcr.io/$PROJECT_ID/utako-jobrunner-${BRANCH_NAME}:latest',
    '-f', 'Dockerfile', '.']

# push container
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/utako-jobrunner-${BRANCH_NAME}:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/utako-jobrunner-${BRANCH_NAME}:${SHORT_SHA}']

# deploy to cloud run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gcloud'
    - 'run'
    - 'deploy'
    - '${_CLOUDRUN_TARGET}'
    - '--image'
    - 'asia.gcr.io/$PROJECT_ID/utako-jobrunner-${BRANCH_NAME}:${SHORT_SHA}'
    - '--platform'
    - 'managed'
    - '--region'
    - 'asia-northeast1'
    - '--no-allow-unauthenticated'
