steps:

# fetch config and analyze model
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud secrets versions access latest --secret=utako-jobrunner-develop-secret > conf/auth.devel.conf']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', 'gs://utako-jobrunner-artifacts/model/model_0.model', 'conf/model_0.model']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', 'gs://utako-jobrunner-artifacts/model/model_0.yaml', 'conf/model_0.yaml']

# build container
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'asia.gcr.io/$PROJECT_ID/utako-jobrunner-${BRANCH_NAME}:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'asia.gcr.io/$PROJECT_ID/utako-jobrunner-${BRANCH_NAME}:latest',
    '-t', 'asia.gcr.io/$PROJECT_ID/utako-jobrunner-${BRANCH_NAME}:${SHORT_SHA}',
    '-f', 'Dockerfile', '.']

# push container
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/utako-jobrunner-${BRANCH_NAME}:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/utako-jobrunner-${BRANCH_NAME}:${SHORT_SHA}']

# deploy to cloud run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'run'
  - 'deploy'
  - 'utako-jobrunner-edge'
  - '--image'
  - 'asia.gcr.io/$PROJECT_ID/utako-jobrunner-${BRANCH_NAME}:${SHORT_SHA}'
  - '--platform'
  - 'managed'
  - '--region'
  - 'asia-northeast-1'
  - '--no-allow-unauthenticated'