# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "master" ]

permissions:
  contents: read

env:
  PYTHONPATH: '.'
  PYTHON_ENV: 'test'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        sudo apt-get install python3-tk libmysqlclient-dev libsndfile1
        python -m pip install --upgrade pip
        pip install codecov
        pip install pipenv
        pipenv install --dev --system --deploy
    - name: Test with pytest
      run: |
        pipenv run test
